In [57]:
import pandas as pd
data = pd.read_csv('Dataset//zomato.csv')

In [58]:

data.shape

(51717, 17)

In [59]:
#split where there is + in phone no and then delte it
data['phone']=data['phone'].str.extract(r'\+91\s*(\d+)')

In [60]:
# data.dropna(subset=['phone'], inplace=True)
data.dropna(subset=['phone'],inplace=True)

In [7]:
data.shape

(39599, 18)

In [61]:
#drop the data in which both of re no

data = data[~((data['book_table']=='No') & (data['online_order']=='No'))]

In [62]:
data.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
5,https://www.zomato.com/bangalore/timepass-dinn...,"37, 5-1, 4th Floor, Bosco Court, Gandhi Bazaar...",Timepass Dinner,Yes,No,3.8/5,286,9980040002,Basavanagudi,Casual Dining,"Onion Rings, Pasta, Kadhai Paneer, Salads, Sal...",North Indian,600,"[('Rated 3.0', 'RATED\n Food 3/5\nAmbience 3/...",[],Buffet,Banashankari
8,https://www.zomato.com/bangalore/penthouse-caf...,"1, 30th Main Road, 3rd Stage, Banashankari, Ba...",Penthouse Cafe,Yes,No,4.0/5,324,8884135549,Banashankari,Cafe,"Pizza, Mocktails, Coffee, Nachos, Salad, Pasta...","Cafe, Italian, Continental",700,"[('Rated 3.0', ""RATED\n I had been to this pl...",[],Cafes,Banashankari
9,https://www.zomato.com/bangalore/smacznego-ban...,"2470, 21 Main Road, 25th Cross, Banashankari, ...",Smacznego,Yes,No,4.2/5,504,9945230807,Banashankari,Cafe,"Waffles, Pasta, Coleslaw Sandwich, Choco Waffl...","Cafe, Mexican, Italian, Momos, Beverages",550,"[('Rated 4.0', ""RATED\n Easy to locate\nVFM 3...",[],Cafes,Banashankari

In [46]:
data.groupby('online_order').size()

online_order
No      1359
Yes    23353
dtype: int64

In [78]:
# data["Client-Id"] = data.index

#reset index make client id in front
data.set_index('Client-Id', inplace=True)

In [79]:
data.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
Client-Id,,,,,,,,,,,,,,,,,
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
2,https://www.zomato.com/bangalore/timepass-dinn...,"37, 5-1, 4th Floor, Bosco Court, Gandhi Bazaar...",Timepass Dinner,Yes,No,3.8/5,286,9980040002,Basavanagudi,Casual Dining,"Onion Rings, Pasta, Kadhai Paneer, Salads, Sal...",North Indian,600,"[('Rated 3.0', 'RATED\n Food 3/5\nAmbience 3/...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/penthouse-caf...,"1, 30th Main Road, 3rd Stage, Banashankari, Ba...",Penthouse Cafe,Yes,No,4.0/5,324,8884135549,Banashankari,Cafe,"Pizza, Mocktails, Coffee, Nachos, Salad, Pasta...","Cafe, Italian, Continental",700,"[('Rated 3.0', ""RATED\n I had been to this pl...",[],Cafes,Banashankari
4,https://www.zomato.com/bangalore/smacznego-ban...,"2470, 21 Main Road, 25th Cross, Banashankari, ...",Smacznego,Yes,No,4.2/5,504,9945230807,Banashankari,Cafe,"Waffles, Pasta, Coleslaw Sandwich, Choco Waffl...","Cafe, Mexican, Italian, Momos, Beverages",550,"[('Rated 4.0', ""RATED\n Easy to locate\nVFM 3...",[],Cafes,Banashankari

In [50]:
#drop column ok
data.drop(columns=['ok'],inplace=True)

In [80]:
#split the adress column into city and country

data[['zipcode', 'city', 'country', 'other']]=data['address'].str.split(',',expand=True,n=3)

In [85]:
# data.drop('city', axis=1, inplace=True)
data.drop('zipcode', axis=1, inplace=True)

In [86]:
data.head()

,url,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city),other
Client-Id,,,,,,,,,,,,,,,,,
0,https://www.zomato.com/bangalore/jalsa-banasha...,Jalsa,Yes,Yes,4.1/5,775,9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,"Banashankari, Bangalore"
1,https://www.zomato.com/SanchurroBangalore?cont...,San Churro Cafe,Yes,No,3.8/5,918,9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,"2nd Stage, Banashankari, Bangalore"
2,https://www.zomato.com/bangalore/timepass-dinn...,Timepass Dinner,Yes,No,3.8/5,286,9980040002,Basavanagudi,Casual Dining,"Onion Rings, Pasta, Kadhai Paneer, Salads, Sal...",North Indian,600,"[('Rated 3.0', 'RATED\n Food 3/5\nAmbience 3/...",[],Buffet,Banashankari,"Bosco Court, Gandhi Bazaar Main Road, Basavan..."
3,https://www.zomato.com/bangalore/penthouse-caf...,Penthouse Cafe,Yes,No,4.0/5,324,8884135549,Banashankari,Cafe,"Pizza, Mocktails, Coffee, Nachos, Salad, Pasta...","Cafe, Italian, Continental",700,"[('Rated 3.0', ""RATED\n I had been to this pl...",[],Cafes,Banashankari,"Banashankari, Bangalore"
4,https://www.zomato.com/bangalore/smacznego-ban...,Smacznego,Yes,No,4.2/5,504,9945230807,Banashankari,Cafe,"Waffles, Pasta, Coleslaw Sandwich, Choco Waffl...","Cafe, Mexican, Italian, Momos, Beverages",550,"[('Rated 4.0', ""RATED\n Easy to locate\nVFM 3...",[],Cafes,Banashankari,"Banashankari, Bangalore"

In [87]:
#want to make country column name to address
data.rename(columns={'other':'address'}, inplace=True)

In [88]:
#want to make adress 2nd column in dataset
cols = data.columns.tolist()
cols = cols[:1] + ['address'] + cols[1:-1]
data = data[cols]

In [89]:
data.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
Client-Id,,,,,,,,,,,,,,,,,
0,https://www.zomato.com/bangalore/jalsa-banasha...,"Banashankari, Bangalore",Jalsa,Yes,Yes,4.1/5,775,9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/SanchurroBangalore?cont...,"2nd Stage, Banashankari, Bangalore",San Churro Cafe,Yes,No,3.8/5,918,9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
2,https://www.zomato.com/bangalore/timepass-dinn...,"Bosco Court, Gandhi Bazaar Main Road, Basavan...",Timepass Dinner,Yes,No,3.8/5,286,9980040002,Basavanagudi,Casual Dining,"Onion Rings, Pasta, Kadhai Paneer, Salads, Sal...",North Indian,600,"[('Rated 3.0', 'RATED\n Food 3/5\nAmbience 3/...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/penthouse-caf...,"Banashankari, Bangalore",Penthouse Cafe,Yes,No,4.0/5,324,8884135549,Banashankari,Cafe,"Pizza, Mocktails, Coffee, Nachos, Salad, Pasta...","Cafe, Italian, Continental",700,"[('Rated 3.0', ""RATED\n I had been to this pl...",[],Cafes,Banashankari
4,https://www.zomato.com/bangalore/smacznego-ban...,"Banashankari, Bangalore",Smacznego,Yes,No,4.2/5,504,9945230807,Banashankari,Cafe,"Waffles, Pasta, Coleslaw Sandwich, Choco Waffl...","Cafe, Mexican, Italian, Momos, Beverages",550,"[('Rated 4.0', ""RATED\n Easy to locate\nVFM 3...",[],Cafes,Banashankari

In [26]:
data.shape

(24712, 17)

In [96]:
# Split on \n and create two columns
#data.dropna(subset=['reviews_list'], inplace=True)
 #Create columns one by one
data['rating_part0'] = data['reviews_list'].str.split('\n').str[0]
data['review_part1'] = data['reviews_list'].str.split('\n').str[1]  # Will be NaN if no second part

In [101]:
data.drop(columns=['review_part1'], inplace=True)

In [102]:
data.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
Client-Id,,,,,,,,,,,,,,,,,
0,https://www.zomato.com/bangalore/jalsa-banasha...,"Banashankari, Bangalore",Jalsa,Yes,Yes,4.1/5,775,9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/SanchurroBangalore?cont...,"2nd Stage, Banashankari, Bangalore",San Churro Cafe,Yes,No,3.8/5,918,9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
2,https://www.zomato.com/bangalore/timepass-dinn...,"Bosco Court, Gandhi Bazaar Main Road, Basavan...",Timepass Dinner,Yes,No,3.8/5,286,9980040002,Basavanagudi,Casual Dining,"Onion Rings, Pasta, Kadhai Paneer, Salads, Sal...",North Indian,600,"[('Rated 3.0', 'RATED\n Food 3/5\nAmbience 3/...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/penthouse-caf...,"Banashankari, Bangalore",Penthouse Cafe,Yes,No,4.0/5,324,8884135549,Banashankari,Cafe,"Pizza, Mocktails, Coffee, Nachos, Salad, Pasta...","Cafe, Italian, Continental",700,"[('Rated 3.0', ""RATED\n I had been to this pl...",[],Cafes,Banashankari
4,https://www.zomato.com/bangalore/smacznego-ban...,"Banashankari, Bangalore",Smacznego,Yes,No,4.2/5,504,9945230807,Banashankari,Cafe,"Waffles, Pasta, Coleslaw Sandwich, Choco Waffl...","Cafe, Mexican, Italian, Momos, Beverages",550,"[('Rated 4.0', ""RATED\n Easy to locate\nVFM 3...",[],Cafes,Banashankari

In [ ]:

data = data.dropna(subset=['name', 'online_order', 'book_table', 'rate', 'votes', 'phone', 'location', 'rest_type', 'cuisines'])

In [114]:
#export data
data.to_csv('Dataset//zomatocleaned.csv', index=True)